import { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  Mic, FileText, ListChecks, Clock, Download, Copy, Check,
  ChevronRight, Headphones, Radio, Volume2, Settings2,
  BookOpen, MessageSquare, Share2, Rss, Calendar, Hash,
  Sparkles, Loader2
} from 'lucide-react';
import { sampleCases } from '../data/cases';
import { useAI } from '../hooks/useAI';

const episodeTemplates = [
  { id: 'single-case', name: 'Single Case Deep Dive', duration: '30-60 min', icon: '🔍' },
  { id: 'cold-case', name: 'Cold Case Spotlight', duration: '20-40 min', icon: '🧊' },
  { id: 'comparison', name: 'Case Comparison', duration: '40-60 min', icon: '⚖️' },
  { id: 'timeline-review', name: 'Timeline Review', duration: '15-30 min', icon: '📅' },
  { id: 'evidence-breakdown', name: 'Evidence Breakdown', duration: '20-40 min', icon: '🔬' },
  { id: 'suspect-profile', name: 'Suspect Profile', duration: '15-30 min', icon: '🕵️' },
  { id: 'listener-theories', name: 'Listener Theories', duration: '30-45 min', icon: '💬' },
  { id: 'news-update', name: 'Case Update / Breaking News', duration: '10-20 min', icon: '📰' },
];

const podcastTools = [
  { icon: FileText, title: 'Script Generator', desc: 'Generate full episode scripts with our AI-powered tool', to: '/script-generator' },
  { icon: ListChecks, title: 'Episode Checklist', desc: 'Pre-production, recording, and post-production checklists' },
  { icon: MessageSquare, title: 'Show Notes Generator', desc: 'Auto-generate show notes with timestamps and links' },
  { icon: Share2, title: 'Social Media Kit', desc: 'Generate promotional content for social platforms' },
  { icon: Rss, title: 'RSS Feed Builder', desc: 'Create and manage your podcast RSS feed' },
  { icon: Calendar, title: 'Content Calendar', desc: 'Plan your episode schedule weeks in advance' },
];

export default function PodcastToolkitPage() {
  const [selectedCase, setSelectedCase] = useState('');
  const [selectedTemplate, setSelectedTemplate] = useState('');
  const [showNotes, setShowNotes] = useState(null);
  const [copied, setCopied] = useState(false);
  const ai = useAI();

  const caseData = selectedCase ? sampleCases.find(c => c.id === parseInt(selectedCase)) : null;

  const handleGenerateShowNotes = async () => {
    if (!caseData) return;
    const template = episodeTemplates.find(t => t.id === selectedTemplate) || episodeTemplates[0];

    try {
      const result = await ai.generateShowNotes(caseData, template);
      setShowNotes(result.content);
    } catch {
      // Fallback to local generation
      generateShowNotesLocal();
    }
  };

  const generateShowNotesLocal = () => {
    if (!caseData) return;

    const template = episodeTemplates.find(t => t.id === selectedTemplate) || episodeTemplates[0];
    const notes = `# ${caseData.title} — Episode Show Notes

## Episode Type: ${template.name}
## Estimated Duration: ${template.duration}

---

## Episode Description
In this episode, we dive deep into ${caseData.title} — a ${caseData.type.toLowerCase()} case from ${caseData.location} dating back to ${new Date(caseData.date).getFullYear()}. ${caseData.summary.split('.')[0]}.

## Key Facts
- **Case Type:** ${caseData.type}
- **Status:** ${caseData.status}
- **Date:** ${new Date(caseData.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
- **Location:** ${caseData.location}
- **Victim(s):** ${caseData.victim}

## Timeline
${caseData.timeline.map(e => `- **${new Date(e.date).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}** — ${e.event}`).join('\n')}

## Key Evidence
${caseData.evidence.map(e => `- ${e}`).join('\n')}

## Suspects / Persons of Interest
${caseData.suspects.map((s, i) => `${i + 1}. ${s}`).join('\n')}

## Discussion Points
- What makes this case significant in true crime history?
- What evidence do you find most compelling?
- What are the strongest theories about what happened?
- What lessons can we learn from how this case was investigated?
${caseData.status === 'Unsolved' ? '- Do you think this case will ever be solved? What would it take?' : '- Was justice truly served in this case?'}

## Tags
${caseData.tags.map(t => `#${t.replace(/\s+/g, '')}`).join(' ')}

## Resources
- [Research this case further on CrimeCase Hub](/cases/${caseData.id})
- [Generate a full script](/script-generator?case=${caseData.id})
- [Find related media](/media?case=${caseData.id})

---
*Generated by CrimeCase Hub — Podcast Toolkit*
`;

    setShowNotes(notes);
  };

  const generateShowNotes = handleGenerateShowNotes;

  const handleCopy = () => {
    if (!showNotes) return;
    navigator.clipboard.writeText(showNotes);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="p-2 bg-green-600/10 rounded-xl">
            <Mic size={24} className="text-green-400" />
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-white" style={{ fontFamily: 'var(--font-display)' }}>
            Podcast Toolkit
          </h1>
        </div>
        <p className="text-zinc-400">
          Everything you need to plan, produce, and promote your true crime podcast
        </p>
      </div>

      {/* Tools Grid */}
      <section className="mb-12">
        <h2 className="text-lg font-bold text-white mb-4">Creator Tools</h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {podcastTools.map((tool, i) => {
            const Icon = tool.icon;
            const content = (
              <div className="group p-5 bg-zinc-900/50 border border-zinc-800/50 rounded-2xl
                          hover:border-zinc-700/50 hover:bg-zinc-900/80 transition-all cursor-pointer">
                <Icon size={24} className="text-green-400 mb-3" />
                <h3 className="font-semibold text-white group-hover:text-green-400 transition-colors mb-1">
                  {tool.title}
                </h3>
                <p className="text-sm text-zinc-400">{tool.desc}</p>
              </div>
            );
            return tool.to ? (
              <Link key={i} to={tool.to}>{content}</Link>
            ) : (
              <div key={i}>{content}</div>
            );
          })}
        </div>
      </section>

      {/* Episode Templates */}
      <section className="mb-12">
        <h2 className="text-lg font-bold text-white mb-4">Episode Templates</h2>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {episodeTemplates.map(template => (
            <button
              key={template.id}
              onClick={() => setSelectedTemplate(template.id)}
              className={`p-4 rounded-xl text-left transition-all ${
                selectedTemplate === template.id
                  ? 'bg-green-600/10 border-2 border-green-600/30'
                  : 'bg-zinc-900/50 border border-zinc-800/50 hover:border-zinc-700/50'
              }`}
            >
              <span className="text-2xl mb-2 block">{template.icon}</span>
              <h3 className="text-sm font-semibold text-white mb-0.5">{template.name}</h3>
              <p className="text-xs text-zinc-500">{template.duration}</p>
            </button>
          ))}
        </div>
      </section>

      {/* Show Notes Generator */}
      <section className="mb-12">
        <h2 className="text-lg font-bold text-white mb-4">Show Notes Generator</h2>
        <div className="grid lg:grid-cols-2 gap-6">
          <div className="bg-zinc-900/50 border border-zinc-800/50 rounded-2xl p-5">
            <div className="space-y-4">
              <div>
                <label className="text-xs font-medium text-zinc-400 uppercase tracking-wider mb-2 block">
                  Select Case
                </label>
                <select
                  value={selectedCase}
                  onChange={e => setSelectedCase(e.target.value)}
                  className="w-full px-3 py-2.5 bg-zinc-800 border border-zinc-700 rounded-xl
                           text-sm text-white outline-none focus:border-green-600"
                >
                  <option value="">Choose a case...</option>
                  {sampleCases.map(c => (
                    <option key={c.id} value={c.id}>{c.title}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="text-xs font-medium text-zinc-400 uppercase tracking-wider mb-2 block">
                  Episode Format
                </label>
                <select
                  value={selectedTemplate}
                  onChange={e => setSelectedTemplate(e.target.value)}
                  className="w-full px-3 py-2.5 bg-zinc-800 border border-zinc-700 rounded-xl
                           text-sm text-white outline-none focus:border-green-600"
                >
                  <option value="">Choose a format...</option>
                  {episodeTemplates.map(t => (
                    <option key={t.id} value={t.id}>{t.icon} {t.name} ({t.duration})</option>
                  ))}
                </select>
              </div>

              {ai.error && (
                <div className="p-3 bg-red-950/50 border border-red-900/30 rounded-xl text-sm text-red-300">
                  AI Error: {ai.error}. Using template generation.
                </div>
              )}

              <button
                onClick={generateShowNotes}
                disabled={!selectedCase || ai.loading}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-green-600
                         hover:bg-green-500 disabled:bg-zinc-800 disabled:text-zinc-600
                         text-white font-semibold rounded-xl transition-all"
              >
                {ai.loading ? (
                  <>
                    <Loader2 size={18} className="animate-spin" />
                    Claude is writing show notes...
                  </>
                ) : (
                  <>
                    <Sparkles size={18} />
                    Generate with AI
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Output */}
          <div className="bg-zinc-900/50 border border-zinc-800/50 rounded-2xl overflow-hidden">
            {showNotes ? (
              <>
                <div className="flex items-center justify-between px-5 py-3 border-b border-zinc-800/50">
                  <span className="text-sm font-medium text-white">Show Notes</span>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1 px-2 py-1 bg-zinc-800 rounded-lg text-xs text-zinc-300
                               hover:text-white transition-colors"
                    >
                      {copied ? <Check size={12} className="text-green-400" /> : <Copy size={12} />}
                      {copied ? 'Copied' : 'Copy'}
                    </button>
                  </div>
                </div>
                <pre className="p-5 text-sm text-zinc-300 whitespace-pre-wrap font-[family-name:var(--font-mono)]
                              overflow-y-auto max-h-96">
                  {showNotes}
                </pre>
              </>
            ) : (
              <div className="flex flex-col items-center justify-center h-full min-h-[300px] text-center px-8">
                <Headphones size={40} className="text-zinc-700 mb-3" />
                <p className="text-zinc-400">Select a case and generate show notes</p>
              </div>
            )}
          </div>
        </div>
      </section>

      {/* Production Checklist */}
      <section>
        <h2 className="text-lg font-bold text-white mb-4">Episode Production Checklist</h2>
        <div className="grid sm:grid-cols-3 gap-4">
          {[
            {
              title: 'Pre-Production',
              items: ['Research case thoroughly', 'Outline episode structure', 'Generate script/notes', 'Prepare discussion points', 'Set up recording equipment', 'Brief co-host (if applicable)']
            },
            {
              title: 'Recording',
              items: ['Sound check & levels', 'Record intro/hook', 'Cover main content', 'Record ad spots', 'Record outro & CTA', 'Back up raw audio']
            },
            {
              title: 'Post-Production',
              items: ['Edit audio & remove errors', 'Add intro/outro music', 'Normalize audio levels', 'Write show notes', 'Create social media graphics', 'Upload & schedule release']
            }
          ].map(phase => (
            <div key={phase.title} className="bg-zinc-900/50 border border-zinc-800/50 rounded-2xl p-5">
              <h3 className="text-sm font-bold text-white mb-3">{phase.title}</h3>
              <div className="space-y-2">
                {phase.items.map((item, i) => (
                  <label key={i} className="flex items-center gap-2 text-sm text-zinc-400 cursor-pointer
                                          hover:text-zinc-300 transition-colors">
                    <input type="checkbox" className="accent-green-600 rounded" />
                    {item}
                  </label>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
